name: build image and deploy

on:
  push:
    branches: ["main"]

jobs:
  do:
    runs-on: ubuntu-latest
    concurrency: build-docker-and-deploy
    steps:
      - uses: actions/checkout@v3
      - name: Set image version (tag)
        id: image_version
        run: echo "githash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Container
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          load: true
          tags: |
            ghcr.io/khaledez/echoinfo:latest
            ghcr.io/khaledez/echoinfo:${{ steps.image_version.outputs.githash }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true