name: deploy docker
on:
  workflow_call:
    inputs:
      instance_ip:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-docker-echoinfo
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set image version (tag)
        id: image_version
        run: echo "githash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: setup ssh agent
        run: |
          mkdir -p $HOME/.ssh
          echo '${{ secrets.SSH_KEY }}' > $HOME/.ssh/github.pem
          chmod 600 $HOME/.ssh/github.pem
          cat <<EOF > $HOME/.ssh/config
          Host ${{ inputs.instance_ip }}
            HostName ${{ inputs.instance_ip }}
            IdentityFile      ~/.ssh/github.pem
            StrictHostKeyChecking no
            IdentitiesOnly    yes
            ControlMaster     auto
            ControlPath       ~/.ssh/control-%C
            ControlPersist    yes
          EOF
          
      - name: login and run
        run: |
          export DOCKER_HOST=ssh://github@${{ inputs.instance_ip }}
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker pull ghcr.io/khaledez/echoinfo:${{ steps.image_version.outputs.githash }}
          docker run -d -e PORT=80 -p 80:80 ghcr.io/khaledez/echoinfo:${{ steps.image_version.outputs.githash }}

      - name: cleanup
        if: always()
        run: rm -rf $HOME/.ssh/github.pem
