name: Release application

on:
  push:
    branches: [ "main" ]

jobs:
  package:
    name: Package release
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    
