name: Release application

on:
  push:
    branches: [ "main" ]

jobs:
  package:
    name: Package release
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci

    - name: build
      run: npm run build

    - name: package
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        tar czvf app-${git_hash}.tar.gz package.json package-lock.json dist/*
        gh release create ${git_hash} ./app-${git_hash}.tar.gz
